/**
 * Human-facing catalogue of server.properties and gamerules, grouped the way a
 * player thinks about them rather than the way the file stores them.
 */

const PROPERTY_GROUPS = [
  {
    id: 'juego',
    title: 'Juego',
    hint: 'Cómo se juega en tu servidor.',
    items: [
      { key: 'gamemode', label: 'Modo de juego', type: 'select', default: 'survival',
        options: [
          ['survival', 'Supervivencia'], ['creative', 'Creativo'],
          ['adventure', 'Aventura'], ['spectator', 'Espectador'],
        ] },
      { key: 'difficulty', label: 'Dificultad', type: 'select', default: 'easy',
        options: [
          ['peaceful', 'Pacífico'], ['easy', 'Fácil'],
          ['normal', 'Normal'], ['hard', 'Difícil'],
        ] },
      { key: 'hardcore', label: 'Modo extremo', type: 'bool', default: 'false',
        help: 'Al morir pasas a espectador permanentemente.' },
      { key: 'pvp', label: 'Combate entre jugadores', type: 'bool', default: 'true' },
      { key: 'force-gamemode', label: 'Forzar modo de juego al entrar', type: 'bool', default: 'false',
        help: 'Devuelve a todos al modo por defecto cada vez que entran.' },
      { key: 'allow-flight', label: 'Permitir volar', type: 'bool', default: 'false',
        help: 'Necesario para mods con alas o jetpacks; si no, el servidor puede expulsar por trampas.' },
      { key: 'allow-nether', label: 'Permitir el Nether', type: 'bool', default: 'true' },
      { key: 'spawn-monsters', label: 'Generar monstruos', type: 'bool', default: 'true' },
      { key: 'spawn-animals', label: 'Generar animales', type: 'bool', default: 'true' },
      { key: 'spawn-npcs', label: 'Generar aldeanos', type: 'bool', default: 'true' },
      { key: 'spawn-protection', label: 'Radio protegido en el spawn', type: 'number', default: '16',
        min: 0, max: 1000, unit: 'bloques',
        help: 'Solo los operadores pueden construir dentro de este radio. 0 lo desactiva.' },
      { key: 'player-idle-timeout', label: 'Expulsar por inactividad', type: 'number', default: '0',
        min: 0, max: 3600, unit: 'min', help: '0 = nunca expulsar.' },
    ],
  },
  {
    id: 'mundo',
    title: 'Mundo',
    hint: 'Se aplican al generar terreno nuevo.',
    items: [
      { key: 'level-name', label: 'Carpeta del mundo', type: 'text', default: 'world',
        help: 'Cambiarlo hace que el servidor use (o cree) otro mundo.' },
      { key: 'level-seed', label: 'Semilla', type: 'text', default: '',
        placeholder: 'Aleatoria', help: 'Solo afecta a mundos nuevos.' },
      { key: 'level-type', label: 'Tipo de mundo', type: 'select', default: 'minecraft:normal',
        options: [
          ['minecraft:normal', 'Normal'], ['minecraft:flat', 'Superplano'],
          ['minecraft:large_biomes', 'Biomas grandes'], ['minecraft:amplified', 'Amplificado'],
          ['minecraft:single_biome_surface', 'Un solo bioma'],
        ] },
      { key: 'generate-structures', label: 'Generar estructuras', type: 'bool', default: 'true',
        help: 'Aldeas, templos, fortalezas…' },
      { key: 'max-world-size', label: 'Tamaño máximo del mundo', type: 'number', default: '29999984',
        min: 1, max: 29999984, unit: 'bloques' },
    ],
  },
  {
    id: 'acceso',
    title: 'Acceso',
    hint: 'Quién puede entrar y cómo se anuncia el servidor.',
    items: [
      { key: 'motd', label: 'Mensaje del servidor', type: 'text', default: 'A Minecraft Server',
        help: 'Se ve bajo el nombre en la lista de servidores.' },
      { key: 'max-players', label: 'Jugadores máximos', type: 'number', default: '20', min: 1, max: 1000 },
      { key: 'online-mode', label: 'Requerir cuenta original', type: 'bool', default: 'true',
        help: 'Desactívalo solo si sabes lo que haces: cualquiera podría entrar con cualquier nombre.' },
      { key: 'white-list', label: 'Solo lista blanca', type: 'bool', default: 'false',
        help: 'Solo entran los jugadores que añadas en la pestaña Jugadores.' },
      { key: 'enforce-whitelist', label: 'Expulsar a los que no estén en la lista', type: 'bool', default: 'false' },
      { key: 'enforce-secure-profile', label: 'Exigir perfil firmado', type: 'bool', default: 'true',
        help: 'Desactívalo si algunos jugadores no pueden conectarse por el chat firmado.' },
      { key: 'hide-online-players', label: 'Ocultar la lista de conectados', type: 'bool', default: 'false' },
      { key: 'server-port', label: 'Puerto', type: 'number', default: '25565', min: 1024, max: 65535,
        help: 'Cámbialo solo si el 25565 ya está ocupado en tu PC.' },
    ],
  },
  {
    id: 'rendimiento',
    title: 'Rendimiento',
    hint: 'Baja estos valores si el servidor va lento.',
    items: [
      { key: 'view-distance', label: 'Distancia de vista', type: 'number', default: '10',
        min: 3, max: 32, unit: 'chunks', help: 'Lo que ven los jugadores. Es lo que más CPU consume.' },
      { key: 'simulation-distance', label: 'Distancia de simulación', type: 'number', default: '10',
        min: 3, max: 32, unit: 'chunks', help: 'Hasta dónde se mueven mobs y crecen cultivos.' },
      { key: 'entity-broadcast-range-percentage', label: 'Alcance de entidades', type: 'number',
        default: '100', min: 10, max: 500, unit: '%' },
      { key: 'network-compression-threshold', label: 'Umbral de compresión', type: 'number',
        default: '256', min: -1, max: 4096, unit: 'bytes' },
      { key: 'pause-when-empty-seconds', label: 'Pausar sin jugadores', type: 'number', default: '60',
        min: 0, max: 3600, unit: 'seg', help: 'Deja de consumir CPU cuando no hay nadie. 0 lo desactiva.' },
      { key: 'sync-chunk-writes', label: 'Escritura síncrona de chunks', type: 'bool', default: 'true',
        help: 'Desactivarlo va más rápido pero es menos seguro ante cortes de luz.' },
    ],
  },
  {
    id: 'recursos',
    title: 'Paquete de recursos',
    hint: 'Texturas que se envían a quien entra.',
    items: [
      { key: 'resource-pack', label: 'URL del paquete', type: 'text', default: '',
        placeholder: 'https://…/pack.zip' },
      { key: 'resource-pack-sha1', label: 'SHA-1 del paquete', type: 'text', default: '',
        help: 'Se calcula solo al pegar la URL.' },
      { key: 'resource-pack-prompt', label: 'Mensaje al proponerlo', type: 'text', default: '' },
      { key: 'require-resource-pack', label: 'Obligatorio', type: 'bool', default: 'false',
        help: 'Expulsa a quien lo rechace.' },
    ],
  },
  {
    id: 'avanzado',
    title: 'Avanzado',
    hint: 'No hace falta tocar esto para jugar.',
    advanced: true,
    items: [
      { key: 'op-permission-level', label: 'Nivel de los operadores', type: 'number', default: '4', min: 1, max: 4 },
      { key: 'function-permission-level', label: 'Nivel de las funciones', type: 'number', default: '2', min: 1, max: 4 },
      { key: 'broadcast-console-to-ops', label: 'Mostrar comandos de consola a los OPs', type: 'bool', default: 'true' },
      { key: 'log-ips', label: 'Registrar direcciones IP', type: 'bool', default: 'true' },
      { key: 'prevent-proxy-connections', label: 'Bloquear conexiones por proxy', type: 'bool', default: 'false',
        help: 'Déjalo desactivado: con un túnel activo bloquearía a tus amigos.' },
      { key: 'enable-command-block', label: 'Activar bloques de comandos', type: 'bool', default: 'false' },
      { key: 'max-tick-time', label: 'Tiempo máximo por tick', type: 'number', default: '60000',
        min: -1, max: 600000, unit: 'ms', help: '-1 desactiva el vigilante que apaga el servidor si se cuelga.' },
      { key: 'rate-limit', label: 'Límite de paquetes', type: 'number', default: '0', min: 0, max: 1000 },
    ],
  },
];

const GAMERULE_GROUPS = [
  {
    id: 'jugador',
    title: 'Al morir y respawn',
    items: [
      { key: 'keepInventory', label: 'Conservar objetos al morir', type: 'bool', default: 'false' },
      { key: 'doImmediateRespawn', label: 'Reaparecer al instante', type: 'bool', default: 'false' },
      { key: 'showDeathMessages', label: 'Anunciar muertes en el chat', type: 'bool', default: 'true' },
      { key: 'spawnRadius', label: 'Radio de reaparición', type: 'number', default: '10', min: 0, max: 1000 },
      { key: 'naturalRegeneration', label: 'Regenerar vida con comida llena', type: 'bool', default: 'true' },
    ],
  },
  {
    id: 'mundo',
    title: 'Mundo y clima',
    items: [
      { key: 'doDaylightCycle', label: 'Ciclo día/noche', type: 'bool', default: 'true' },
      { key: 'doWeatherCycle', label: 'Ciclo del clima', type: 'bool', default: 'true' },
      { key: 'doFireTick', label: 'El fuego se propaga', type: 'bool', default: 'true' },
      { key: 'mobGriefing', label: 'Los mobs destruyen bloques', type: 'bool', default: 'true',
        help: 'Creepers, endermans y ghasts. Desactívalo para proteger construcciones.' },
      { key: 'doMobSpawning', label: 'Aparición natural de mobs', type: 'bool', default: 'true' },
      { key: 'randomTickSpeed', label: 'Velocidad de crecimiento', type: 'number', default: '3', min: 0, max: 4096,
        help: 'Cultivos y propagación. Subirlo mucho penaliza el rendimiento.' },
      { key: 'doInsomnia', label: 'Aparecen phantoms', type: 'bool', default: 'true' },
      { key: 'doPatrolSpawning', label: 'Patrullas de saqueadores', type: 'bool', default: 'true' },
      { key: 'doTraderSpawning', label: 'Aparece el mercader errante', type: 'bool', default: 'true' },
    ],
  },
  {
    id: 'progreso',
    title: 'Progreso y objetos',
    items: [
      { key: 'doMobLoot', label: 'Los mobs sueltan objetos', type: 'bool', default: 'true' },
      { key: 'doTileDrops', label: 'Los bloques sueltan objetos', type: 'bool', default: 'true' },
      { key: 'doEntityDrops', label: 'Vehículos sueltan objetos', type: 'bool', default: 'true' },
      { key: 'announceAdvancements', label: 'Anunciar logros', type: 'bool', default: 'true' },
      { key: 'keepInventoryOnDimensionChange', label: 'Conservar al cambiar dimensión', type: 'bool', default: 'true' },
      { key: 'fallDamage', label: 'Daño por caída', type: 'bool', default: 'true' },
      { key: 'fireDamage', label: 'Daño por fuego', type: 'bool', default: 'true' },
      { key: 'drowningDamage', label: 'Daño por ahogo', type: 'bool', default: 'true' },
    ],
  },
  {
    id: 'servidor',
    title: 'Servidor',
    items: [
      { key: 'sendCommandFeedback', label: 'Confirmar comandos en el chat', type: 'bool', default: 'true' },
      { key: 'commandBlockOutput', label: 'Salida de bloques de comandos', type: 'bool', default: 'true' },
      { key: 'logAdminCommands', label: 'Registrar comandos de admin', type: 'bool', default: 'true' },
      { key: 'reducedDebugInfo', label: 'Ocultar coordenadas (F3)', type: 'bool', default: 'false' },
      { key: 'playersSleepingPercentage', label: 'Jugadores para pasar la noche', type: 'number',
        default: '100', min: 0, max: 100, unit: '%',
        help: 'Bájalo para que no haga falta que duerman todos.' },
      { key: 'maxEntityCramming', label: 'Máx. entidades apiladas', type: 'number', default: '24', min: 0, max: 100 },
    ],
  },
];

module.exports = { PROPERTY_GROUPS, GAMERULE_GROUPS };
